spring:
  datasource:
    url: jdbc:mysql://localhost:3306/lhmbe
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true

logging:
  level:
    root: INFO
